#!/bin/bash
#Remove repo stuff
rm -rf .vim
rm -f .bashrc
rm -f .bash_aliases
rm -f .vimrc
#Copy local stuff over
cp -r ~/.vim .
cp ~/.bashrc .
cp ~/.bash_aliases .
cp ~/.vimrc .
#Remove the Session.vim and Bundles
rm .vim/Session.vim
rm -rf ./vim/bundle/*
