#!/bin/bash
#Remove local
rm -f ~/.bashrc
rm -f ~/.bash_aliases
rm -rf ~/.vim
rm -f ~/.vimrc
#Copy to local
cp -r .vim ~/
cp .bashrc ~/
cp .bash_aliases ~/
cp .vimrc ~/
#Bring over Vundle
rm -rf ~/.vim/bundle/
git clone https://github.com/VundleVim/Vundle.vim ~/.vim/bundle/Vundle.vim
echo 'Done, make sure to run :PluginInstall in Vim'
